Change account addresses to be checksum
Taraxa-project/taraxa-platform pull request #117
Opened 2022-03-28 16:57 UTC by farebord

Fixes #112

2022-03-28 19:32 UTC, VargaElod23 requested changes

2022-03-29 14:07 UTC, farebord commented on services/community-site/src/pages/Delegation/Modal/Undelegate.tsx
> +  const checksumAccount = ethers.utils.getAddress(account || '');
I agree that looks much cleaner.

2022-03-29 18:54 UTC, farebord commented on services/community-site/src/pages/Delegation/Modal/Undelegate.tsx
> +  const checksumAccount = ethers.utils.getAddress(account || '');
@VargaElod23 Please review!

2022-03-29 19:13 UTC, Elod23 approved these changes
Way to go. LGTM 💪🏻

2022-03-30 16:02 UTC, merged