Feature/explorer fix connection switch
Taraxa-project/taraxa-platform pull request #327
Opened 2023-01-03 15:38 UTC by VargaElod23

2023-01-03 15:50 UTC, Malak67 requested changes
Small changes needed

2023-01-03 15:50 UTC, Malak67 commented on services/explorer/src/index.tsx
> +export let API = TESTNET_API;
I would move this back to types.ts or where we declare all the endpoints as we don't want to import it from here.

2023-01-03 15:50 UTC, Malak67 commented on services/explorer/src/api/explorer-api/fetchDagsByAddress.ts
> +import { API } from '../../index';
This should be moved back (same for the other hooks).

2023-01-03 15:50 UTC, Malak67 commented on services/explorer/src/utils/networks.ts
> +  const network = localStorage.getItem(SELECTED_NETWORK);
We should not take the network directly from localStorage. There is a a hook useNetworkSelection which sets inside the context the current network (and it has a logic on deciding if it takes it first based on the curent domain or local storage and so on). So this method should receive the network as parameter.

2023-01-03 15:50 UTC, Malak67 commented on services/explorer/src/utils/networks.ts
> +export const recreateAPIConnection = (): string => {
This should also receive the network as parameter.

2023-01-03 15:50 UTC, Malak67 commented on services/explorer/src/index.tsx
> +    url: recreateGraphQLConnection(),
React the currentNetwork from the context:
`const { currentNetwork } = useExplorerNetwork();`
And then pass it to the two methods.

2023-01-03 15:57 UTC, rattrap requested changes
Don't like a few things:
1. We know the URLs for mainnet, testnet and devnet. We don't need env vars for those. Let's just hardcode them like here - https://github.com/Taraxa-project/taraxa-platform/blob/feature/moves_mainnet_to_onchain_economics/services/community-site/src/utils/networks.ts#L15
2. Don't like the global variable thing. We have the network in the context, let's use the context
3. I think we can do better than reloading

2023-01-03 19:06 UTC, Malak67 approved these changes

2023-01-05 13:02 UTC, rattrap approved these changes

2023-01-05 13:02 UTC, merged