Feature/handle stale transactions
Taraxa-project/taraxa-platform pull request #370
Opened 2023-01-31 11:20 UTC by VargaElod23

2023-01-31 12:58 UTC, rattrap requested changes

2023-01-31 12:58 UTC, rattrap commented on services/explorer-indexer/src/modules/health/producerHealthIndicator.ts
> +        if (this.dagService) {
`this.txService`

2023-01-31 12:58 UTC, rattrap commented on services/explorer-indexer/src/modules/health/syncerHealthIndicator.ts
> +        if (this.dagService) {
`this.txService`

2023-01-31 12:58 UTC, rattrap commented on services/explorer-indexer/src/modules/historical-sync/historical.syncer.module.ts
> +import { Queues } from 'src/types';
Relative imports

2023-01-31 12:58 UTC, rattrap commented on services/explorer-indexer/src/modules/pbft/pbft.consumer.ts
> +    if (!pbft.transactions && pbft.transactions?.length === 0) return;
I think you wanted to have an or here

2023-01-31 12:58 UTC, rattrap commented on services/explorer-indexer/src/modules/pbft/pbft.consumer.ts
> +            !transaction.value
We already check these

2023-01-31 12:58 UTC, rattrap commented on services/explorer-indexer/src/modules/pbft/pbft.consumer.ts
> +          await this.txQueue.add(QueueJobs.STALE_TRANSACTIONS, {
If it failed in the try, why wouldn't it fail in the catch?

2023-02-01 10:14 UTC, Malak67 approved these changes

2023-02-01 10:48 UTC, merged