Feature/add subgraph for dpos
Taraxa-project/taraxa-platform pull request #390
Opened 2023-02-24 15:08 UTC by VargaElod23

2023-02-24 15:41 UTC, Malak67 submitted a review, later dismissed
LGTM

2023-05-15 09:01 UTC, rattrap requested changes
There's no need to store the undelegations. These can be queried from the contract

2023-05-15 09:01 UTC, rattrap commented on packages/dpos-subgraph/schema.graphql
> +  validator: String!
Let's add the date here too.

2023-05-15 09:11 UTC, rattrap requested changes

2023-05-15 09:11 UTC, rattrap commented on packages/dpos-subgraph/src/mapping.ts
> +  const commission = event.params.commission;
I think we can normalise the commission here to 0-100%

2023-05-15 10:10 UTC, rattrap commented on packages/dpos-subgraph/schema.graphql
> +  validator: String!
Yes. That's fine.

2023-05-15 10:10 UTC, rattrap commented on packages/dpos-subgraph/src/mapping.ts
> +  const commission = event.params.commission;
I understand. Let's keep it as is then.

2023-05-15 10:11 UTC, VargaElod23 commented on packages/dpos-subgraph/schema.graphql
> +  validator: String!
Cool, I'll be adding it in that manner then

2023-05-15 13:39 UTC, Malak67 approved these changes

2023-05-16 13:36 UTC, merged