feat(explorer) Adjusted network selection
Taraxa-project/taraxa-platform pull request #416
Opened 2023-03-21 16:16 UTC by Malak67

2023-03-21 17:24 UTC, rattrap requested changes

2023-03-21 17:24 UTC, rattrap commented on services/explorer/src/utils/networks.ts
> +      window.location.replace(`https://explorer.taraxa.io`);
For mainnet it should also be `https://mainnet.explorer.taraxa.io`

2023-03-21 17:24 UTC, rattrap commented on services/explorer/src/utils/networks.ts
> +      window.location.replace(`https://explorer.taraxa.io`);
Same here

2023-03-22 10:46 UTC, rattrap requested changes

2023-03-22 11:00 UTC, Malak67 commented on services/explorer/src/components/AddressInfo/AddressDetails.tsx
> +              } / TARA )`}
Yes, I missed those.

2023-03-22 11:04 UTC, VargaElod23 approved these changes

2023-03-22 12:00 UTC, merged