adds hook for undelegation check
Taraxa-project/taraxa-platform pull request #524
Opened 2023-06-14 15:48 UTC by VargaElod23

2023-06-15 10:30 UTC, Malak67 submitted a review, later dismissed

2023-06-15 12:44 UTC, rattrap requested changes

2023-06-15 12:44 UTC, rattrap commented on services/community-site/src/pages/Staking/NodeProfilePage.tsx
> +  }, [address]);
Add account to dep array

2023-06-16 13:19 UTC, rattrap approved these changes

2023-06-16 13:20 UTC, merged