Feat/541/hex to dec
Taraxa-project/taraxa-platform pull request #554
Opened 2023-08-22 11:16 UTC by Malak67

Closes #541

2023-08-22 12:01 UTC, VargaElod23 approved these changes
LGTM 👍🏼

2023-08-22 13:04 UTC, VargaElod23 requested changes

2023-08-22 13:04 UTC, VargaElod23 commented on services/explorer/src/pages/TransactionData/TopicDataDisplay.tsx
> +        const addressHex = '0x' + hexValue.slice(-40);
I just checked and this is the wrong way of doing it. This converts the address to decimal. However, on a log's topics we have only addresses, so all we need to do is to cut the padded zeroes to make the address readable.

2023-08-22 13:04 UTC, VargaElod23 commented on services/explorer/src/pages/TransactionData/EventDataDisplay.tsx
> +        setDecoded(addressDecimal);
![image](https://github.com/Taraxa-project/taraxa-platform/assets/100562086/412ce3b4-297e-417c-8ba4-e98310be9032)

This fails on empty data

2023-08-22 13:06 UTC, VargaElod23 commented on services/explorer/src/pages/TransactionData/TopicDataDisplay.tsx
> +        const addressHex = '0x' + hexValue.slice(-40);
Example: https://etherscan.io/tx/0x9051b74a7a2be1c071453f6b0ff076ab0173b07bb647927933c292c85a8f7076#eventlog

2023-08-22 14:13 UTC, VargaElod23 commented on services/explorer/src/pages/TransactionData/EventDataDisplay.tsx
> +        setDecoded(addressDecimal);
Also, this won't work like this as we don't know the primitive that comes in here as base, so we should remove this. The main idea for this was to add a `decimal <> hex switch to the tx values and the block numbers` for debug purposes.

2023-08-23 10:08 UTC, VargaElod23 approved these changes

2023-08-25 10:24 UTC, rattrap approved these changes

2023-08-25 10:29 UTC, merged